---
driver:
  name: vagrant
  customize:
    memory: 2048
  synced_folders:
    - ["../", "/home/vagrant/workspace"]
  network:
    - ["forwarded_port", {guest: 3000, host: 4001}]
    - ["forwarded_port", {guest: 9292, host: 5001}]

provisioner:
  name: chef_solo

platforms:
  - name: kitchen-box
    driver:
      box: ubuntu/trusty64

suites:
  - name: chef-workshop
    run_list:
      - chef-workshop-cookbook
